### PR TITLE
Added usage instructions in readme

### PR DESCRIPTION
**Pull request by prateekrastogi**

### CODE REVIEW

**Comment by Jamim** [comment]
Hello @prateekrastogi,

Thank you for the effort!
It would be nice if you squash your changes into a single commit.

Thanks!

**Comment by prateekrastogi** [comment]
Hi,

Hope this works. :-) 

Also, upon running `pio train`, i am getting error in training due to ur algo looking for es instance in 127.0.0.1:9200. It seems that we also need to  open es port on localhost in docker-compose file. Will  create a separate issue detailing that issue later on.

**Comment by thuandt** [comment]
@prateekrastogi thanks for your PR.

This image run as sameway in PIO docs, you can also override `ES_HOST` for pointing into ES run inside docker (see `docker-compose.yml` and `conf/pio-env.sh` for reference)

**Comment by prateekrastogi** [comment]
@thuandt Although, it might be working properly on linux without any issues. I encountered an spark es dns resolution issue while using 'pio train' with ur, and basically the error message was:

Exception in thread "main" org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot detect ES version - typically this happens if the network/Elasticsearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'es.nodes.wan.only'
        at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:294)
        at org.elasticsearch.spark.rdd.EsSpark$.doSaveToEs(EsSpark.scala:103)
        at org.elasticsearch.spark.rdd.EsSpark$.saveToEs(EsSpark.scala:79)
        at org.elasticsearch.spark.rdd.EsSpark$.saveToEs(EsSpark.scala:76)
        at org.elasticsearch.spark.package$SparkRDDFunctions.saveToEs(package.scala:56)
        at com.actionml.EsClient$.hotSwap(EsClient.scala:313)
        at com.actionml.URModel.save(URModel.scala:82)
        at com.actionml.URAlgorithm.calcAll(URAlgorithm.scala:367)
        at com.actionml.URAlgorithm.train(URAlgorithm.scala:295)
        at com.actionml.URAlgorithm.train(URAlgorithm.scala:180)
        at org.apache.predictionio.controller.P2LAlgorithm.trainBase(P2LAlgorithm.scala:49)
        at org.apache.predictionio.controller.Engine$$anonfun$18.apply(Engine.scala:690)
        at org.apache.predictionio.controller.Engine$$anonfun$18.apply(Engine.scala:690)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:285)
        at org.apache.predictionio.controller.Engine$.train(Engine.scala:690)
        at org.apache.predictionio.controller.Engine.train(Engine.scala:176)
        at org.apache.predictionio.workflow.CoreWorkflow$.runTrain(CoreWorkflow.scala:67)
        at org.apache.predictionio.workflow.CreateWorkflow$.main(CreateWorkflow.scala:251)
        at org.apache.predictionio.workflow.CreateWorkflow.main(CreateWorkflow.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[localhost:9200]]
        at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:150)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:461)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:425)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:429)
        at org.elasticsearch.hadoop.rest.RestClient.get(RestClient.java:155)
        at org.elasticsearch.hadoop.rest.RestClient.remoteEsVersion(RestClient.java:655)
        at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:287)

I did manged to fix this issue by changing sparkconfig of 'engine.json' stored in default working directory of app to:

 "sparkConf": {
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer",
    "spark.kryo.registrator": "org.apache.mahout.sparkbindings.io.MahoutKryoRegistrator",
    "spark.kryo.referenceTracking": "false",
    "spark.kryoserializer.buffer": "300m",
    "es.index.auto.create": "true",
    "es.nodes": "host.docker.internal",
    "es.nodes.wan.only": "true"
  },

Also, i edited docker-compose to open elasticsearch container port on 9200 on localhost, the changes to elasticsearch service were basically:

  elasticsearch:
    image: inspectorio/elasticsearch-without-xpack
    ports:
    - 9200:9200

Finally, i manged to successfully pass through pio train stage. Since, 'host.docker.internal' can be used only on windows to refer on localhost, I am not sure about correct config for unix. Will update when I run it on linux.

**Comment by thuandt** [comment]
@prateekrastogi I faced same problem with you about dns when point to different ES cluster setup

Depend on your cluster setup, you can add params for your `pio train` with `--conf spark.es.nodes.client.only=true` or `--conf spark.es.nodes.wan.only=true`.

in our k8s cluster, `ES_HOST` must be FDQN domain like `es.default.svc.local`

**Comment by prateekrastogi** [comment]
@thuandt  Thank you for assistance. Although, I did managed to run pio train successfully, but some issue in inserting/updating engine instance is causing pio deploy to exit with error. Here are relevant error logs of pio train stage:

[INFO] [CoreWorkflow$] Updating engine instance
[ERROR] [ESEngineInstances] Failed to update pio_meta/engine_instances/AWenQXSyT0osKTf4vmK-
[INFO] [CoreWorkflow$] Training completed successfully.

Also, pio deploy exit with following error:

pio deploy
[ERROR] [Engine$] No valid engine instance found for engine com.actionml.RecommendationEngine da5c765435adbd8d2010cf07337422fdd38b20dd.
Try running 'train' before 'deploy'. Aborting.

Please provide any guidance to fix that issue,  if you can. It's clear that issue is arising due to being unable to write training model to es instance, but running pio status shows no error. Also, pio train is weirdly completing without exiting.

**Comment by thuandt** [comment]
@prateekrastogi Did you try with `"algorithms" -> "params" -> "numESWriteConnections": 1` in `engine.json`?

**Comment by prateekrastogi** [comment]
@thuandt  Thank you again. Just tried it. Although, it's not working, but looking at the container logs I found mismatch in the  pio_meta instance showing on docker-compose terminal and where pio train is trying to write, the relevant lines are: 

On docker-compose command run console:
elasticsearch_1  | [2018-12-14T06:45:23,465][INFO ][o.e.c.m.MetaDataMappingService] [5jISdjA] [pio_meta/uzSx5KrASEWUI5D0gyg3Qg] create_mapping [channels]

Vs pio train terminal:

[ERROR] [ESEngineInstances] Failed to update pio_meta/engine_instances/AWerhICPoDgXQ9cOcKcG

I think the issue might be some issue due to state corruption on docker-machine instance as I have been noticing write attempt on same pio_meta instance on each subsequent clean run of pio train. Will try cleaning everything and see if that works after work.

**Comment by prateekrastogi** [comment]
@thuandt  Just tried it with clean config, but it seems apparently both output are different even in that scenario. Also, setting eswriteconnection to 1 is not working. Are both output different in your dev environment too?

**Comment by nguyentrucdn** [comment]
@prateekrastogi can you copy here the engine.json file, docker-compose file and full command you are using to run the training job?

**Comment by prateekrastogi** [comment]
@nguyentrucdn  Hi. Here are the run configs, in which pio train was supposedly successful:

https://gist.github.com/prateekrastogi/204cacdcaf30ad95ccac1d290bf589e0

In config 2, rest of the configs were same to config 1.

**Comment by nguyentrucdn** [comment]
@prateekrastogi could you try to run training command with spark memory options as below:
`pio train  -- --driver-memory 4g --executor-memory 4g`

**Comment by prateekrastogi** [comment]
@nguyentrucdn On running `pio train` with the flag you mentioned, I am still getting the same error.  To me the issue seem to primarily lie in writing to es docker instance as mentioned in earlier comments. Even using the default docker hub elasticsearch container v 5.6.8, together with setting no. of numESWriteConnections to 1, is not working. Analyzing the es instance reveals that pio_meta index is being created, but somehow writing trained model to it is failing which might probably have been originated due to permissions issue of chown used in dockerfile. However, that's just a guess.

**Comment by nguyentrucdn** [comment]
@prateekrastogi 
Could you modify the engine.json to add `numESWriteConnections` configuration as below:
```
  "algorithms": [
    {
      "comment": "simplest setup where all values are default, popularity based backfill, must add eventsNames",
      "name": "ur",
      "params": {
        "appName": "handmade",
        "indexName": "urindex",
        "typeName": "items",
        "comment": "must have data for the first event or the model will not build, other events are optional",
        "eventNames": ["watch"],
       "numESWriteConnections": 1
      }
    }
  ]
```
Moreover, please increase the capacity of the docker machine (in my PC: 4 cpus, 10GB Ram).

**Comment by prateekrastogi** [comment]
@nguyentrucdn Still getting the same error :-( . Here's the output:

Of `pio train -- --driver-memory 4g --executor-memory 4g`

[INFO] [URModel] Group all properties RDD
[INFO] [URModel] ES fields[5]: List(item-isRemoved, popRank, itemType, id, watch)
[INFO] [EsClient$] Create new index: urindex_1545380213868, items, List(item-isRemoved, popRank, itemType, id, watch), Map(popRank -> (float,false), watch -> (keyword,true))
[INFO] [EsClient$] defaultParallelism: 4
[INFO] [EsClient$] Coalesce to: 1 to reduce number of ES connections for saveToEs
[INFO] [Engine$] org.apache.predictionio.data.storage.NullModel does not support data sanity check. Skipping check.
[INFO] [Engine$] EngineWorkflow.train completed
[INFO] [Engine] engineInstanceId=AWfP1mKGBlI9ORrqCvRC
[INFO] [CoreWorkflow$] Inserting persistent model
[INFO] [CoreWorkflow$] Updating engine instance
[ERROR] [ESEngineInstances] Failed to update pio_meta/engine_instances/AWfP1mKGBlI9ORrqCvRC
[INFO] [CoreWorkflow$] Training completed successfully.

Of the docker-compose terminal running whole cluster:

elasticsearch_1  | [2018-12-21T07:42:27,286][INFO ][o.e.h.n.Netty4HttpServerTransport] [lkdu0iw] publish_address {172.19.0.3:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch_1  | [2018-12-21T07:42:27,286][INFO ][o.e.n.Node               ] [lkdu0iw] started
elasticsearch_1  | [2018-12-21T07:42:27,312][INFO ][o.e.g.GatewayService     ] [lkdu0iw] recovered [0] indices into cluster_state
elasticsearch_1  | [2018-12-21T07:43:05,427][INFO ][o.e.c.m.MetaDataCreateIndexService] [lkdu0iw] [pio_meta] creating index, cause [api], templates [], shards [5]/[1], mappings []
elasticsearch_1  | [2018-12-21T07:43:05,851][INFO ][o.e.c.m.MetaDataMappingService] [lkdu0iw] [pio_meta/N_Rbc7BkSuen5oovlMhVsQ] create_mapping [engine_instances]
elasticsearch_1  | [2018-12-21T07:43:05,944][INFO ][o.e.c.m.MetaDataMappingService] [lkdu0iw] [pio_meta/N_Rbc7BkSuen5oovlMhVsQ] create_mapping [sequences]
elasticsearch_1  | [2018-12-21T07:43:06,039][INFO ][o.e.c.m.MetaDataMappingService] [lkdu0iw] [pio_meta/N_Rbc7BkSuen5oovlMhVsQ] create_mapping [evaluation_instances]
elasticsearch_1  | [2018-12-21T07:43:06,146][INFO ][o.e.c.m.MetaDataMappingService] [lkdu0iw] [pio_meta/N_Rbc7BkSuen5oovlMhVsQ] create_mapping [apps]
elasticsearch_1  | [2018-12-21T07:43:06,221][INFO ][o.e.c.m.MetaDataMappingService] [lkdu0iw] [pio_meta/N_Rbc7BkSuen5oovlMhVsQ] create_mapping [accesskeys]
elasticsearch_1  | [2018-12-21T07:43:50,373][INFO ][o.e.c.m.MetaDataMappingService] [lkdu0iw] [pio_meta/N_Rbc7BkSuen5oovlMhVsQ] update_mapping [accesskeys]
elasticsearch_1  | [2018-12-21T07:44:17,483][INFO ][o.e.c.m.MetaDataMappingService] [lkdu0iw] [pio_meta/N_Rbc7BkSuen5oovlMhVsQ] create_mapping [channels]
elasticsearch_1  | [2018-12-21T08:15:18,353][INFO ][o.e.c.m.MetaDataCreateIndexService] [lkdu0iw] [urindex_1545380118056] creating index, cause [api], templates [], shards [5]/[1], mappings [items]
elasticsearch_1  | [2018-12-21T08:16:54,142][INFO ][o.e.c.m.MetaDataCreateIndexService] [lkdu0iw] [urindex_1545380213868] creating index, cause [api], templates [], shards [5]/[1], mappings [items]
elasticsearch_1  | [2018-12-21T08:16:55,731][INFO ][o.e.c.m.MetaDataDeleteIndexService] [lkdu0iw] [urindex_1545380118056/MjyLF60SQKiSOixFb7Pcsw] deleting index

**Pull request merged**
